"""Main entry point for Tech News Hook."""

import asyncio
import logging
from datetime import UTC, datetime

from bot_common.discord_utils import split_message
from bot_common.tavily_client import TavilyClient
from bot_common.zai_client import ZaiClient
from discord_webhook import DiscordEmbed, DiscordWebhook

from tech_news.config import Config
from tech_news.content_generator import ContentGenerator

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def main():
    """Run the tech news generator and send to Discord."""
    config = Config.from_env()

    if not config.DISCORD_WEBHOOK_TECH_NEWS:
        logger.error("DISCORD_WEBHOOK_TECH_NEWS not set. Exiting.")
        return

    # Initialize services
    zai_client = ZaiClient(api_key=config.ZAI_API_KEY)
    tavily_client = TavilyClient(api_key=config.TAVILY_API_KEY)
    generator = ContentGenerator(zai_client, tavily_client)

    # Generate Content
    content = await generator.generate_news()

    # Publish to Discord
    webhook = DiscordWebhook(url=config.DISCORD_WEBHOOK_TECH_NEWS)

    chunks = split_message(content)

    for i, chunk in enumerate(chunks):
        title = f"📰 Tech News Digest: {datetime.now(UTC).strftime('%Y-%m-%d')}"
        if len(chunks) > 1:
            title += f" ({i + 1}/{len(chunks)})"

        # Create Embed
        embed = DiscordEmbed(
            title=title,
            description=chunk,
            color="ff9900",  # Orange for News
        )
        embed.set_footer(text=f"Generated by GLM-4.7 • {datetime.now(UTC).strftime('%Y-%m-%d')}")

        webhook.add_embed(embed)

        # Execute in thread to avoid blocking async loop
        response = await asyncio.to_thread(webhook.execute)

        if response.status_code == 200:
            logger.info(f"Successfully sent chunk {i + 1}/{len(chunks)} to Discord.")
        else:
            logger.error(
                f"Failed to send chunk {i + 1} to Discord: {response.status_code} {response.text}"
            )

        # Clear embeds for next chunk
        webhook.remove_embeds()


if __name__ == "__main__":
    asyncio.run(main())
