"""Main entry point for Tech Interview Hook."""

import asyncio
import logging
from datetime import UTC, datetime

from bot_common.discord_utils import send_discord_embeds
from bot_common.tavily_client import TavilyClient
from bot_common.zai_client import ZaiClient

from coding_interview.config import Config
from coding_interview.constants import EMBED_COLOR
from coding_interview.content_generator import ContentGenerator
from coding_interview.topic_selector import TopicSelector

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def main():
    """Run the interview question generator."""
    config = Config.from_env()

    if not config.DISCORD_WEBHOOK_URL:
        logger.error("DISCORD_WEBHOOK_TECH_INTERVIEW not set. Exiting.")
        return

    # Initialize services
    zai_client = ZaiClient(api_key=config.ZAI_API_KEY)
    tavily_client = TavilyClient(api_key=config.TAVILY_API_KEY)
    selector = TopicSelector()
    generator = ContentGenerator(zai_client, tavily_client)

    # 1. Select Topic
    topic_data = selector.get_random_topic()
    topic = topic_data["content"]
    topic_type = topic_data["type"]
    logger.info(f"Selected topic: {topic} ({topic_type})")

    # 2. Generate Content
    try:
        content = await generator.generate_interview_question(topic, topic_type)
    except Exception as e:
        logger.error(f"Failed to generate content: {e}")
        return

    # 3. Publish to Discord

    await send_discord_embeds(
        webhook_url=config.DISCORD_WEBHOOK_URL,
        title_prefix=f"🧠 Tech Interview Drill: {topic}",
        content=content,
        color=EMBED_COLOR,
        footer_text=f"Generated by GLM-4.7 • {datetime.now(UTC).strftime('%Y-%m-%d')}",
    )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as e:
        logger.exception(f"Unhandled exception in Tech Interview Hook: {e}")
