"""Main entry point for Tech Knowledge Hook."""

import asyncio
import logging
from datetime import UTC, datetime

from bot_common.tavily_client import TavilyClient
from bot_common.zai_client import ZaiClient
from discord_webhook import DiscordEmbed, DiscordWebhook
from tech_knowledge.config import Config
from tech_knowledge.content_generator import ContentGenerator
from tech_knowledge.topic_selector import TopicSelector

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def main():
    """Run the knowledge generator."""
    config = Config.from_env()

    if not config.DISCORD_WEBHOOK_URL:
        logger.error("DISCORD_WEBHOOK_TECH_KNOWLEDGE not set. Exiting.")
        # Optional: You might want to raise an error or exit gracefully based on requirements
        return

    # Initialize services
    zai_client = ZaiClient(api_key=config.ZAI_API_KEY)
    tavily_client = TavilyClient(api_key=config.TAVILY_API_KEY)
    selector = TopicSelector()
    generator = ContentGenerator(zai_client, tavily_client)

    # 1. Select Topic
    topic = selector.get_random_topic()
    logger.info(f"Selected topic: {topic}")

    # 2. Generate Content
    content = await generator.generate_knowledge(topic)

    # 3. Publish to Discord
    webhook = DiscordWebhook(url=config.DISCORD_WEBHOOK_URL)

    # Create Embed
    embed = DiscordEmbed(
        title=f"⚡ Tech Knowledge Drop: {topic}",
        description=content[:4096],  # Discord limit
        color="0099ff",  # Blue for Tech
    )
    embed.set_footer(text=f"Generated by GLM-4.7 • {datetime.now(UTC).strftime('%Y-%m-%d')}")

    webhook.add_embed(embed)

    response = webhook.execute()
    if response.status_code == 200:
        logger.info("Successfully sent to Discord.")
    else:
        logger.error(f"Failed to send to Discord: {response.status_code} {response.text}")


if __name__ == "__main__":
    asyncio.run(main())
