"""Selects topics for tech knowledge generation."""

import random

# Curated list of high-value technical topics
TECH_TOPICS = [
    # Python
    "Python Asyncio: Event Loops & Couroutines",
    "Python Decorators: Best Practices",
    "Python Type Hints & Mypy",
    "Python Context Managers (with statement)",
    "Python Generators & Iterators",
    "Python Global Interpreter Lock (GIL)",
    "Python Data Classes vs Pydantic",
    "Python functools",
    "Python built-in functions: map, filter, reduce",
    "Python modules, decorators, and metaclasses",
    "Python Hashing and Equality: __hash__ vs __eq__",
    "Python Array and linked list implementations",
    "Python Hashmaps and dictionaries",
    "Python Heaps, Stacks, and Queues",
    "Python Regular Expressions: re module",
    "Python Binary search trees and balanced trees",
    "Python Multithreading vs Multiprocessing",
    "Python sorting algorithms",
    "Write pyproject.toml for a Python project",
    "Python List Comprehensions vs Generator Expressions",
    "Python Paradigms",
    "Python context managers",
    "Python File handling and I/O operations",
    "Python testing",
    # Backend / System Design
    "Database Indexing Strategies (B-Tree vs Hash)",
    "CAP Theorem in Distributed Systems",
    "Caching Strategies (Write-through vs Write-back)",
    "ACID Explained: Atomic, Consistent, Isolated & Durable",
    "Multi-Version Concurrency Control (MVCC) in Databases",
    "Write Ahead Log (WAL)",
    "Query Processing in PostgreSQL",
    "Constraints in PostgreSQL",
    "PostgreSQL Tuples",
    "Schemas in PostgreSQL",
    "PostgreSQL Transaction Isolation Levels",
    "For Tables in PostgreSQL",
    "Data Types in PostgreSQL",
    "Querying data with Data Manipulation Language (DML) in PostgreSQL",
    "Filtering Data in PostgreSQL",
    "Modifying Data in PostgreSQL",
    "Joining Tables in PostgreSQL",
    "Import and Export using COPY in PostgreSQL",
    "Transactions in PostgreSQL",
    "Common Table Expressions (CTEs) in PostgreSQL",
    "Subqueries in PostgreSQL",
    "Grouping in PostgreSQL",
    "Lateral Join in PostgreSQL",
    "Set Operations in PostgreSQL",
    "Window Functions in PostgreSQL",
    "PostgreSQL Indexes B-Tree vs Hash, GiST, GIN, BRIN, SPGist",
    "Process and Memory architecture of PostgreSQL",
    "Vacuum Processing in PostgreSQL",
    "Buffer Management in PostgreSQL",
    "Lock Management in PostgreSQL",
    "System Catalogs in PostgreSQL",
    "PL/pgSQL: PostgreSQL's Procedural Language",
    "Postgresql functions and stored procedures",
    "Triggering events in PostgreSQL",
    "Recursion CTEs in PostgreSQL",
    "Aggregate functions in PostgreSQL",
    "Pandas Data Structures: Understanding Series and DataFrames",
    "Loading Data with Pandas: read_csv(), read_excel(), read_json()",
    "Data Inspection in Pandas: head(), tail(), info(), describe(), shape",
    "Handling Missing Data in Pandas: isnull(), dropna(), fillna()",
    "Data Selection and Filtering in Pandas: loc, iloc, boolean indexing",
    "Data Cleaning in Pandas: Renaming columns, changing data types, removing duplicates",
    "Data Manipulation in Pandas: apply(), map(), applymap()",
    "Data Aggregation in Pandas: groupby()",
    "Merging and Joining in Pandas: concat(), merge(), join()",
    "Reshaping Data in Pandas: pivot_table(), melt()",
    "Datetime Parsing in Pandas: to_datetime()",
    "Index Manipulation in Pandas: Setting and resetting date indices",
    "Resampling and Shifting in Pandas: resample(), shift()",
]


class TopicSelector:
    """Selects a topic for the knowledge drop."""

    def get_random_topic(self) -> str:
        """Return a random topic from the curated list."""
        return random.choice(TECH_TOPICS)
