"""Main entry point for English Grammar Hook."""

import asyncio
import logging
from datetime import UTC, datetime

from bot_common.discord_utils import send_discord_embeds
from bot_common.tavily_client import TavilyClient
from bot_common.zai_client import ZaiClient

from tech_interview.config import Config
from tech_interview.constants import EMBED_COLOR
from tech_interview.content_generator import ContentGenerator
from tech_interview.topic_selector import TopicSelector

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def main():
    """Run the grammar lesson generator."""
    config = Config.from_env()

    if not config.DISCORD_WEBHOOK_URL:
        logger.error("DISCORD_WEBHOOK_TECH_INTERVIEW not set. Exiting.")
        return

    # Initialize services
    zai_client = ZaiClient(api_key=config.ZAI_API_KEY)
    tavily_client = TavilyClient(api_key=config.TAVILY_API_KEY)
    selector = TopicSelector()
    generator = ContentGenerator(zai_client, tavily_client)

    # 1. Select Topic
    topic = selector.get_random_topic()
    logger.info("Selected topic: %s", topic)

    # 2. Generate Content
    try:
        content = await generator.generate_grammar_lesson(topic)
    except Exception:
        logger.exception("Failed to generate content")
        return

    # 3. Publish to Discord
    await send_discord_embeds(
        webhook_url=config.DISCORD_WEBHOOK_URL,
        title_prefix=f"📚 Grammar Drop: {topic}",
        content=content,
        color=EMBED_COLOR,
        footer_text=f"Generated by GLM-4.7 • {datetime.now(UTC).strftime('%Y-%m-%d')}",
    )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception:
        logger.exception("Unhandled exception in English Grammar Hook")
